version: '3'

services:

  test:
    build: .
    command: ./bin/run.sh
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=testroot
    depends_on:
      - secretsmanager
      - vault

  secretsmanager:
    image: localstack/localstack
    environment:
      - SERVICES=secretsmanager

  vault:
    image: vault
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=testroot